---
- name: Install Apache and Upload my Web Page
  hosts: all
  become: yes

  vars:
   source_folder: ./MyWebSite2
   destin_folder: /var/www/html

  tasks:
  - name: Check and Pring LINUX Version
    debug: var=ansible_os_family

  - block: # ******* RedHat Block *********
    - name: Install Apache Web Server for RedHat
      yum: name=httpd state=latest

    - name: Start WebServer and make it enable on boot for RedHat
      service: name=httpd state=started enabled=yes
    when: ansible_os_family == 'RedHat'

  
  - block: # ******* Debian Block *********
    - name: Install Apache Web Server for Debian
      apt: name=apache2 state=latest

    - name: Start WebServer and make it enable on boot for Debian
      service: name=apache2 state=started enabled=yes
    when: ansible_os_family == 'Debian'

  - name: Generate INDEX.HTML file from JINJA template
    # generate index.html from jinja template
    template: src={{ source_folder }}/index.j2 dest={{ destin_folder }}/index.html mode=0555
    notify: 
      - Restart Apache RedHat
      - Restart Apache Debian

  - name: Copy MyHomePage to Server for RedHat
    #  copy: src={{ item }} dest={{ destin_folder }} mode=0555                       # with fileglob
    copy: src={{ source_folder }}/{{ item }} dest={{ destin_folder }} mode=0555 # with loop
    # with_fileglob: "{{ source_folder }}/*.*"  # copy everything from folder
    loop:
      - "t1.txt"
    notify: 
      - Restart Apache RedHat
      - Restart Apache Debian

  handlers:
  - name: Restart Apache RedHat
    service: name=httpd state=restarted
    when: ansible_os_family == 'RedHat'

  - name: Restart Apache Debian
    service: name=apache2 state=restarted
    when: ansible_os_family == 'Debian'
 
