---
# tasks file for deploy_apache_web
- block: # ******* RedHat Block *********
  - name: Install Apache Web Server for RedHat
    yum: name=httpd state=latest

  - name: Start WebServer and make it enable on boot for RedHat
    service: name=httpd state=started enabled=yes
  when: ansible_os_family == 'RedHat'

  
- block: # ******* Debian Block *********
  - name: Install Apache Web Server for Debian
    apt: name=apache2 state=latest

  - name: Start WebServer and make it enable on boot for Debian
    service: name=apache2 state=started enabled=yes
  when: ansible_os_family == 'Debian'

- name: Generate INDEX.HTML file from JINJA template
  # generate index.html from jinja template
  template: src=index.j2 dest={{ destin_folder }}/index.html mode=0555
  notify: 
    - Restart Apache RedHat
    - Restart Apache Debian

- name: Copy MyHomePage to Server for RedHat
  #  copy: src={{ item }} dest={{ destin_folder }} mode=0555                       # with fileglob
  copy: src={{ item }} dest={{ destin_folder }} mode=0555 # with loop
  # with_fileglob: "{{ source_folder }}/*.*"  # copy everything from folder
  loop:
    - "t1.txt"
  notify: 
    - Restart Apache RedHat
    - Restart Apache Debian